/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRegisterIndexRouteImport } from './routes/_public/register/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as PublicHomeIndexRouteImport } from './routes/_public/_home/index'
import { Route as PrivateAccountIndexRouteImport } from './routes/_private/account/index'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterIndexRoute = PublicRegisterIndexRouteImport.update({
  id: '/_public/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHomeIndexRoute = PublicHomeIndexRouteImport.update({
  id: '/_public/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAccountIndexRoute = PrivateAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicHomeIndexRoute
  '/account/': typeof PrivateAccountIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/register/': typeof PublicRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicHomeIndexRoute
  '/account': typeof PrivateAccountIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/register': typeof PublicRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_private/account/': typeof PrivateAccountIndexRoute
  '/_public/_home/': typeof PublicHomeIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account/' | '/login/' | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/login' | '/register'
  id:
    | '__root__'
    | '/_private'
    | '/_private/account/'
    | '/_public/_home/'
    | '/_public/login/'
    | '/_public/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicHomeIndexRoute: typeof PublicHomeIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof PublicRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_home/': {
      id: '/_public/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/account/': {
      id: '/_private/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof PrivateAccountIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateAccountIndexRoute: typeof PrivateAccountIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAccountIndexRoute: PrivateAccountIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicHomeIndexRoute: PublicHomeIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
